# Exemples Algebra

In [1]:
import numpy as np

* Exemples de vectors (array)

In [2]:
v=np.array([1,0,0])
u=np.array([0,-2,0])

In [4]:
print(u)

[ 0 -2  0]


Operacions amb vectors (suma, resta, producte escalar i vectorial)

In [5]:
w1=u+v
print(w1)
w2=u-v
print(w2)

[ 1 -2  0]
[-1 -2  0]


In [7]:
a=np.dot(u,v)
print(a)

0


In [9]:
b=np.cross(v,u)
print(b)

[ 0  0 -2]


* Exemples amb Matrius

In [13]:
A=np.array([[2,4],[1,3]])
print(A)

[[2 4]
 [1 3]]


In [16]:
e=A[1,0]
print(e)

1


In [17]:
v=A[0,:]
print(v)

[2 4]


In [18]:
u=A[:,1]
print(u)

[4 3]


Valors i vectors propis

In [19]:
A=np.array([[2,2],[1,3]])

In [23]:
Valors,Vectors = np.linalg.eig(A)
print("Valors propis", Valors)
print("Vectors propis",Vectors)

Valors propis [1. 4.]
Vectors propis [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [24]:
u=Vectors[:,0]
print(u)

[-0.89442719  0.4472136 ]


In [25]:
v=Vectors[:,1]
print(v)

[-0.70710678 -0.70710678]


comprovem que efectivament son vectors propis 

In [27]:
z=np.dot(A,u)
print(z)

[-0.89442719  0.4472136 ]


In [28]:
z2=np.dot(A,v)
print(z2)

[-2.82842712 -2.82842712]


ALtres exemples de matrius

In [29]:
A=np.zeros([3,3])
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
